replicaCount: 1

image:
  repository: cloudketan/node-project
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30007

containerPort: 3000

env:
  ENVIRONMENT: Dev